services:
  backend:
    build:
      context: ./dental-office-backend 
      dockerfile: Dockerfile           
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=dbpassword
      - DB_NAME=dental_office
      - JWT_SECRET=d140a2dddfeb22e7d81d235875a5ac2edd0beff15a2874cb219a5748e1d53532
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: dental_office
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: